sudo: false
language: rust
branches:
  only:
  - master

cache: cargo

matrix:
  fast_finish: false
  include:
    - rust: stable

addons:
  apt:
    packages:
      - libudev-dev
      - libssl-dev
      - pkg-config

script:
  - cargo check --all
  - cargo test --all
