[package]
name = "solaris"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
ethabi = { git = "https://github.com/tomusdrw/ethabi.git" }
ethcore = { git = "https://github.com/paritytech/parity.git", branch = "td-evm" }
ethcore-bigint = { git = "https://github.com/paritytech/parity.git", branch = "td-evm" }
ethcore-bytes = { git = "https://github.com/paritytech/parity.git", branch = "td-evm" }
ethereum-types = { git = "https://github.com/paritytech/primitives.git" }
evm = { git = "https://github.com/paritytech/parity.git", branch = "td-evm" }
lazy_static = "0.2"
vm = { git = "https://github.com/paritytech/parity.git", branch = "td-evm" }

