[package]
name = "solaris"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
ethcore-bytes = { path = "../../parity/util/bytes" }
ethcore-bigint = { path = "../../parity/util/bigint", version = "0.2" }
# ethabi = "4.2"
ethabi = { git = "https://github.com/tomusdrw/ethabi.git" }
# ethcore = { git = "https://github.com/paritytech/parity.git" }
ethcore  = { path = "../../parity/ethcore" }
ethereum-types = { git = "https://github.com/paritytech/primitives.git" }
lazy_static = "0.2"
vm  = { path = "../../parity/ethcore/vm" }
evm  = { path = "../../parity/ethcore/evm" }
# vm = { git = "https://github.com/paritytech/parity.git" }

